### ISSUE TITLE
Incomings calls are not added app._pendingCalls

### ISSUE THREAD

**Issue by zbowling** [bminer/node-twilio-api#11]
When a status callback comes in for that call, it doesn't know who the call is for and throws an error.

2012-04-27T20:51:28+00:00 app[web.1]: Error: Twilio submitted call status for a call that does not exist.
2012-04-27T20:51:28+00:00 app[web.1]:     at /app/node_modules/twilio-api/lib/Application.js:297:11
2012-04-27T20:51:28+00:00 app[web.1]:     at HTTPParser.onMessageComplete (http.js:137:23)
2012-04-27T20:51:28+00:00 app[web.1]:     at IncomingMessage.emit (events.js:64:17)
2012-04-27T20:51:28+00:00 app[web.1]:     at Socket.ondata (http.js:1410:22)
2012-04-27T20:51:28+00:00 app[web.1]:     at afterBodyParser (/app/node_modules/twilio-api/lib/Application.js:181:6)

**Comment by bminer** [comment]
You are correct.  Yes, this is definitely a bug.  Right around [line 264](https://github.com/bminer/node-twilio-api/blob/master/lib/Application.js#L264), there should be code to add the Call object to the app._pendingCalls object.  I'll submit a quick patch, but I won't have time to test it.  Would you be willing to test it and get back to me with the results?

**Comment by zbowling** [comment]
Yeah! I'm cheating in my app and I'm writing your private var after the incoming event and adding the call to the array. Kind of seemed it needed to be a little refactored (not really "pending"... Just the term is confusing)

**Comment by bminer** [comment]
Agreed, "pending" is a bit confusing.  Maybe the term "activeCalls" would be more appropriate?  Anyway, fix coming soon.  :)

**Comment by bminer** [comment]
Published 0.2.2 in NPM
